WITH

CHURNERSCRM AS(
    SELECT DISTINCT ACT_ACCT_CD,MAX(ACT_ACCT_INST_DT) AS MinFechaInst, MAX(CST_CHRN_DT) AS Maxfecha
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_CRM_BULK_FILE_FINAL_HISTORIC_DATA_2021_D`
    --WHERE PD_BB_PROD_ID IS NOT NULL
    --WHERE PD_TV_PROD_ID IS NOT NULL
    WHERE PD_VO_PROD_ID IS NOT NULL
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT (MONTH FROM Maxfecha) = EXTRACT (MONTH FROM MAX(FECHA_EXTRACCION))
    AND EXTRACT(MONTH FROM MaxFecha)=9
),

GRUPOSANUALES AS(
SELECT DISTINCT ACT_ACCT_CD,
CASE WHEN DATE_DIFF(MaxFecha, MinFechaInst, DAY)<=90 AND MinFechaInst<MaxFecha THEN "<3M"
WHEN DATE_DIFF(MaxFecha, MinFechaInst, DAY)<=180 AND DATE_DIFF(MaxFecha, MinFechaInst, DAY)>90 THEN "03-6M"
WHEN DATE_DIFF(MaxFecha, MinFechaInst, DAY)<=270 AND DATE_DIFF(MaxFecha, MinFechaInst, DAY)>180 THEN "06-9M"
WHEN DATE_DIFF(MaxFecha, MinFechaInst, DAY)<=365 AND DATE_DIFF(MaxFecha, MinFechaInst, DAY)>270 THEN "09-1A"
WHEN DATE_DIFF(MaxFecha, MinFechaInst, DAY)<=720 AND DATE_DIFF(MaxFecha, MinFechaInst, DAY)>365 THEN "1A-2A"
WHEN DATE_DIFF(MaxFecha, MinFechaInst, DAY)<=1080 AND DATE_DIFF(MaxFecha, MinFechaInst, DAY)>720 THEN "2A-3A"
WHEN DATE_DIFF(MaxFecha, MinFechaInst, DAY)<=1440 AND DATE_DIFF(MaxFecha, MinFechaInst, DAY)>1080 THEN "3A-4A"
WHEN DATE_DIFF(MaxFecha, MinFechaInst, DAY)>1440 THEN ">4A" END AS GRUPITOS
FROM CHURNERSCRM
)

SELECT 
--*
GRUPITOS, COUNT(DISTINCT ACT_ACCT_CD)
FROM GRUPOSANUALES 
GROUP BY GRUPITOS ORDER BY GRUPITOS
--ORDER BY ACT_ACCT_CD

