WITH 

ACTIVOS AS (
SELECT DISTINCT ACT_ACCT_CD, FECHA_EXTRACCION, C_CUST_AGE, ACT_ACCT_INST_DT
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_CRM_BULK_FILE_FINAL_HISTORIC_DATA_2021_D`
WHERE FECHA_EXTRACCION ="2021-12-31"
GROUP BY ACT_ACCT_CD, FECHA_EXTRACCION, C_CUST_AGE, ACT_ACCT_INST_DT)

SELECT COUNT(DISTINCT ACT_ACCT_CD) 
FROM ACTIVOS 
--WHERE DATE_DIFF(FECHA_EXTRACCION, DATE(ACT_ACCT_INST_DT), DAY)<=990
where DATE_DIFF(FECHA_EXTRACCION, DATE(ACT_ACCT_INST_DT), DAY)>990
--order by ACT_ACCT_CD
