WITH

CHURNERSCRM AS(
    SELECT DISTINCT ACT_ACCT_CD,MIN(ACT_ACCT_INST_DT) AS MinFechaInst, MAX(CST_CHRN_DT) AS Maxfecha
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_CRM_BULK_FILE_FINAL_HISTORIC_DATA_2021_D`
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT (MONTH FROM Maxfecha) = EXTRACT (MONTH FROM MAX(FECHA_EXTRACCION))
    AND EXTRACT(MONTH FROM MaxFecha)=8
),

GRUPOSANUALES AS(
SELECT DISTINCT ACT_ACCT_CD,
CASE WHEN DATE_DIFF(MaxFecha, MinFechaInst, DAY)<=90 AND MinFechaInst<MaxFecha THEN "<3M"
WHEN DATE_DIFF(MaxFecha, MinFechaInst, DAY)<=180 AND DATE_DIFF(MaxFecha, MinFechaInst, DAY)>90 THEN "03-6M"
WHEN DATE_DIFF(MaxFecha, MinFechaInst, DAY)<=270 AND DATE_DIFF(MaxFecha, MinFechaInst, DAY)>180 THEN "06-9M"
WHEN DATE_DIFF(MaxFecha, MinFechaInst, DAY)<=360 AND DATE_DIFF(MaxFecha, MinFechaInst, DAY)>270 THEN "09-1A"
WHEN DATE_DIFF(MaxFecha, MinFechaInst, DAY)<=450 AND DATE_DIFF(MaxFecha, MinFechaInst, DAY)>360 THEN "12-15M"
WHEN DATE_DIFF(MaxFecha, MinFechaInst, DAY)<=540 AND DATE_DIFF(MaxFecha, MinFechaInst, DAY)>450 THEN "15-18M"
WHEN DATE_DIFF(MaxFecha, MinFechaInst, DAY)<=630 AND DATE_DIFF(MaxFecha, MinFechaInst, DAY)>540 THEN "18-21M"
WHEN DATE_DIFF(MaxFecha, MinFechaInst, DAY)<=720 AND DATE_DIFF(MaxFecha, MinFechaInst, DAY)>630 THEN "21-2A"
WHEN DATE_DIFF(MaxFecha, MinFechaInst, DAY)<=810 AND DATE_DIFF(MaxFecha, MinFechaInst, DAY)>720 THEN "24-27M"
WHEN DATE_DIFF(MaxFecha, MinFechaInst, DAY)<=900 AND DATE_DIFF(MaxFecha, MinFechaInst, DAY)>810 THEN "27-30M"
WHEN DATE_DIFF(MaxFecha, MinFechaInst, DAY)<=990 AND DATE_DIFF(MaxFecha, MinFechaInst, DAY)>900 THEN "30-33M"
WHEN DATE_DIFF(MaxFecha, MinFechaInst, DAY)<=1080 AND DATE_DIFF(MaxFecha, MinFechaInst, DAY)>990 THEN "33-3A"
WHEN DATE_DIFF(MaxFecha, MinFechaInst, DAY)>1080 THEN ">3A" END AS GRUPITOS
FROM CHURNERSCRM
)

SELECT 
--*
GRUPITOS, COUNT(DISTINCT ACT_ACCT_CD)
FROM GRUPOSANUALES 
--WHERE DATE_DIFF(MaxFecha, MinFechaInst, DAY)<=1080
--AND DATE_DIFF(MaxFecha, MinFechaInst, DAY)>1080
GROUP BY GRUPITOS ORDER BY GRUPITOS
--ORDER BY ACT_ACCT_CD

